vaadin.launch-browser=true
spring.application.name=midas
spring.datasource.url=jdbc:sqlite:midas.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.jpa.show-sql=true
# Midas Defaults
midas.i18n.default-language=en