spring.application.name=midas-demo
server.port=8082
spring.datasource.url=jdbc:sqlite:midas-demo.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# Languages
midas.i18n.default-locale=en
#midas.i18n.default-locale=de

# Demo specific settings
logging.file.name=logs/midas-demo.log
