# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created

name: Maven Package

on:
  release:
    types: [ created ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Set version from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "Setting project version to $VERSION"
          mvn -B versions:set -DnewVersion=$VERSION -DgenerateBackupPoms=false

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Package Release Assets
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          mkdir midas-distribution
          cp target/midas.jar midas-distribution/
          zip -r midas-$VERSION.zip midas-distribution/

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: midas-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
